default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool: 5
  username: khristine
  password: your_password

development:
  adapter: postgresql
  encoding: unicode
  database: my_app_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: khristine
  username: khristine_user
  password: <%= ENV['cXbXXUZQ5N3y1TVaiLz4svn0kWenkLL'] %>
  host: <%= ENV['dpg-ct7duj9u0jms73dpmj60-a'] %>
  secret_key_base: <%= ENV['d02c2cbe7ff122c443233c7df205a85e29310b6f39d8eefaffd66c5cb3bc2387834014a88bd29f78543e3ac0c581a4d4a8fe0abcfe6f5f92d3ebbb7a30b1f295'] %>


  # database: <%= ENV['postgresql://khristine_user:qcXbXXUZQ5N3y1TVaiLz4svn0kWenkLL@dpg-ct7duj9u0jms73dpmj60-a.oregon-postgres.render.com/khristine'] %> # Use the DATABASE_URL environment variable
  